name: Checks
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
